// <auto-generated />
using Kolokwium.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kolokwium.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kolokwium.Models.ObjectOwner", b =>
                {
                    b.Property<int>("ObjectId")
                        .HasColumnType("int");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.HasKey("ObjectId", "OwnerId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Object_Owner");

                    b.HasData(
                        new
                        {
                            ObjectId = 1,
                            OwnerId = 1
                        });
                });

            modelBuilder.Entity("Kolokwium.Models.ObjectType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Object_Type");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "object1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "object2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "object3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "object4"
                        });
                });

            modelBuilder.Entity("Kolokwium.Models.Objects", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("ObjectTypeId")
                        .HasColumnType("int");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ObjectTypeId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Object");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Height = 4,
                            ObjectTypeId = 1,
                            WarehouseId = 1,
                            Width = 5
                        });
                });

            modelBuilder.Entity("Kolokwium.Models.Owner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.HasKey("Id");

                    b.ToTable("Owner");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Marek",
                            LastName = "Adamski",
                            PhoneNumber = "777333111"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Aleksandra",
                            LastName = "Wiśniewska",
                            PhoneNumber = "999111444"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Jan",
                            LastName = "Kowalski",
                            PhoneNumber = "555333111"
                        });
                });

            modelBuilder.Entity("Kolokwium.Models.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Warehouse");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "war1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "war2"
                        });
                });

            modelBuilder.Entity("Kolokwium.Models.ObjectOwner", b =>
                {
                    b.HasOne("Kolokwium.Models.Objects", "Object")
                        .WithMany("ObjectOwners")
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kolokwium.Models.Owner", "Owner")
                        .WithMany("ObjectOwners")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Object");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Kolokwium.Models.Objects", b =>
                {
                    b.HasOne("Kolokwium.Models.ObjectType", "ObjectType")
                        .WithMany("Objects")
                        .HasForeignKey("ObjectTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kolokwium.Models.Warehouse", "Warehouse")
                        .WithMany("Objects")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ObjectType");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Kolokwium.Models.ObjectType", b =>
                {
                    b.Navigation("Objects");
                });

            modelBuilder.Entity("Kolokwium.Models.Objects", b =>
                {
                    b.Navigation("ObjectOwners");
                });

            modelBuilder.Entity("Kolokwium.Models.Owner", b =>
                {
                    b.Navigation("ObjectOwners");
                });

            modelBuilder.Entity("Kolokwium.Models.Warehouse", b =>
                {
                    b.Navigation("Objects");
                });
#pragma warning restore 612, 618
        }
    }
}
